services:  
  main:
    build:
      target: dev
    volumes:
      - ../backend/main/app:/project/app
      - ../logging.yaml:/logging/logging.yaml:ro
    image: codetam/igloo-main:dev
    command: sleep infinity

  frontend:
    build:
      target: dev
    volumes:
      - ../frontend/app:/app
      - /app/node_modules
      - /app/.pnpm-store
      - ../logging.yaml:/logging/logging.yaml:ro
    image: codetam/igloo-frontend:dev